### ISSUE TITLE
tutorial addition

### ISSUE THREAD

**Issue by Whitford** [smog-server/OpenSMOG#16]
For the tutorial using a CA model.  We should also include the steps required to generate the model. We can also provide the files, but I think it is important for the tutorial to take a user through the full pipeline.

**Comment by Whitford** [comment]
This could be added a separate page that describes how to generate the force field for 2ci2.

First, one only wants to keep the ATOM lines.  Note that, sometimes, you also want HETATMs.  This is up to the user.  HETATMs can be things that we don't want to include (e.g. HOH), or things that we may want to included (e.g. posttranslational modifications).  In this case, we only want ATOM lines.

> grep "^ATOM" 2ci2.pdb > 2ci2.atoms.pdb

Add an END line to the 2ci2.atoms.pdb

Adjust the file, so that the naming convention conforms with the default models

> smog_adjustPDB -i 2ci2.atoms.pdb -o 2ci2.adj.pdb

Use the adjusted file to generate your input CA model

> smog2 -i 2ci2.adj.pdb -CA -dname 2ci2.CA -openSMOG 



We can also add an all-atom example.  of course, the only differences would be that -CA because -AA, the cutoff should be shorter with the AA model and the timestep should be larger.

**Comment by jknoel** [comment]
I just came by to request the same thing. It shows the smog2 parameters in the .top file, but not everyone knows that. Additionally, the pdb file used to generate the CA files is not included, but it should be there.

**Comment by jknoel** [comment]
@Whitford Note that the timestep for the CA simulation in the tutorial is 0.002; I think that is longer than we consider "standard"

**Comment by contessoto** [comment]
The tutorial of using SMOG2 for generating the models is now included in the docs.
I also updated the tutorials for running the simulation both for C-alpha and AA models.
