### ISSUE TITLE
Issue while installing smog2.4pre1 with conda

### ISSUE THREAD

**Issue by Sandra-Byju** [smog-server/OpenSMOG#25]
Followed all the steps as given in opensmog manual to install smog2.4pre1 with conda and all packages were successfully insatlled.
But smog2 gave the error,
Can't load '/home/sandra.byju/anaconda3/envs/smog2.4pre1/lib/site_perl/5.26.2/x86_64-linux-thread-multi/auto/XML/LibXML/LibXML.so' for module XML::LibXML: /lib64/libc.so.6: version `GLIBC_2.15' not found (required by /home/sandra.byju/anaconda3/envs/smog2.4pre1/lib/site_perl/5.26.2/x86_64-linux-thread-multi/auto/XML/LibXML/../../../../../../libxml2.so.2) at /home/sandra.byju/anaconda3/envs/smog2.4pre1/lib/5.26.2/x86_64-linux-thread-multi/DynaLoader.pm line 193.
 at /home/sandra.byju/anaconda3/envs/smog2.4pre1/lib/site_perl/5.26.2/x86_64-linux-thread-multi/XML/LibXML.pm line 156.
BEGIN failed--compilation aborted at /home/sandra.byju/anaconda3/envs/smog2.4pre1/lib/site_perl/5.26.2/x86_64-linux-thread-multi/XML/LibXML.pm line 156.
Compilation failed in require at /home/sandra.byju/smog_git/smog2.4pre/smog-2.4-pre1/src/openSMOG.pm line 35.
BEGIN failed--compilation aborted at /home/sandra.byju/smog_git/smog2.4pre/smog-2.4-pre1/src/openSMOG.pm line 35.
Compilation failed in require at /home/sandra.byju/smog_git/smog2.4pre/smog-2.4-pre1/src/templateParser.pm line 41.
BEGIN failed--compilation aborted at /home/sandra.byju/smog_git/smog2.4pre/smog-2.4-pre1/src/templateParser.pm line 41.
Compilation failed in require at /home/sandra.byju/smog_git/smog2.4pre/smog-2.4-pre1/src/smogv2 line 29.
BEGIN failed--compilation aborted at /home/sandra.byju/smog_git/smog2.4pre/smog-2.4-pre1/src/smogv2 line 29.

Went ahead and installed $conda install -c asmeurer glibc

This lead to a different smog2 error. 
/home/sandra.byju/smog_git/smog2.4pre/smog-2.4-pre1/bin/smog2: line 6: 19431 Segmentation fault      (core dumped) /home/sandra.byju/anaconda3/envs/smog2.4pre1/bin/perl /home/sandra.byju/smog_git/smog2.4pre/smog-2.4-pre1/src/smogv2 "$@"

Then I uninstalled glibc, 
$ conda uninstall glibc

And smog2 worked. 
$ ./test-config
Found smog2 ... running basic tests ...
test: 1AKEapo_v2 AA
test: 1AKEapo_v2 CA
test: 1AKEapo_v2 AAgauss
test: 2GIS_noSAM_v2 AA
test: 2GIS_noSAM_v2 AAgauss
Tests passed.

Attaching terminal output which shows each step performed.
[installation.txt](https://github.com/smog-server/OpenSMOG/files/6973726/installation.txt)

**Comment by contessoto** [comment]
I am closing this since smog2 installation worked after a few additional steps. Thanks for reporting this.
