### ISSUE TITLE
readthedocs history

### ISSUE THREAD

**Issue by Whitford** [smog-server/OpenSMOG#34]
Do we have a version history somewhere?  It can be very useful for people to know what is changing with each release. For example, if someone happened to use 1.0.2 and nothing worked, then they can't say that we did not warn them.  Also, is there a way to make 1.0.0-1.0.2 inaccessible through conda?  There is no reason to allow people to install something that we know is broken.

**Comment by contessoto** [comment]
The versioned  documentation do not show all the details of the code functions. There is a minor difference between the main release tag and the Docs branch. The version history is based on the main release tag which is not used for building the documentation.

**Comment by Whitford** [comment]
Where is this history? This can be something manually posted, like for smog2. 

https://smog-server.org/smog2/history.html

Is there something like this?  Basically, something that we annotate so that we can tell people what is new and when bugs were found/fixed?

**Comment by contessoto** [comment]
This info is added on each release on GitHub. People can track the modifications there.
I will make "active" the other released versions on read the docs but it will show nothing on the module page.

**Comment by Whitford** [comment]
Sounds good.

**Comment by contessoto** [comment]
I am closing it since we have the documentation versioned.
