### ISSUE TITLE
another cryptic error

### ISSUE THREAD

**Issue by Whitford** [smog-server/OpenSMOG#36]
similar to issue #35 

>>> sbm_CA2.createReporters(trajectory=True, energies=True, energy_components=False, interval=1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/whitford/miniconda3/envs/openSMOG/lib/python3.9/site-packages/OpenSMOG/OpenSMOG.py", line 378, in createReporters
    self.simulation.reporters.append(DCDReporter(dcdfile, interval))
**AttributeError: 'SBM' object has no attribute 'simulation'**
>>> sbm_CA2.createSimulation()
>>> sbm_CA2.createReporters(trajectory=True, energies=True, energy_components=False, interval=1)

**Comment by junioreif** [comment]
A check function was created to check if setup_openmm() was setup before using LoadSystem()
