### ISSUE TITLE
Weird temperature

### ISSUE THREAD

**Issue by Whitford** [smog-server/OpenSMOG#39]
Since we give temperature in reduced units, we should write it in reduced units.

This is in the energies file.

"Temperature (K)"

**Comment by contessoto** [comment]
The header info comes from openmm reporter class. There is no room for modifying these names.

**Comment by Whitford** [comment]
We need to do something about it.  It doesn't make sense to tell people we are using reduced units, and we then write out non-reduced units.  Any ideas of how to convert the label and values?  It shouldn't be hard to do.

**Comment by contessoto** [comment]
Yep. I know. Openmm reporter is similar to Gromacs output that also writes the temperature in K.
Modifying the openmm core is not an option but we should be able to work around the header only.

**Comment by Whitford** [comment]
Great.

**Comment by Whitford** [comment]
Another possibility is to redefine the boltzmann constant.  Then, we don't need to convert our temperature to non-reduced units.

**Comment by Whitford** [comment]
Since the boltzmann constant is defined in a common constants file, we can't easily overwrite it.  I agree this is a pain to deal with.  We should just put a note somewhere about this limitation in the I/O

**Comment by Whitford** [comment]
It will be quite a hassle to do this properly.  For now, we just provide a description of units in the help() method.  We can come back to this someday.

**Comment by junioreif** [comment]
I take a look at this issue. 

The only solution will be to recreate the reporter (the same as forcesReporter).

**Comment by junioreif** [comment]
Issue solved by new stateReport function.
