### ISSUE TITLE
Request for help in performing multi-basin model

### ISSUE THREAD

**Issue by chemlove** [smog-server/OpenSMOG#58]
Dear all,

I am a beginner of the structure-based model and see the multi-basin model has been adopted in several papers to study the conformational change of biomolecules. However, there are few guidelines for performing simulations with the multi-basin model in the SMOG server/tutorial/manual.

Can you tell me how to construct the input file which can be used in multi-basin simulations? Any command lines of scripts are appreciated.

One more question:

Can the SBM_AA-amber-bonds be used with the Gaussian contact potentials? 

If the answer is YES, how can I combine them together since they are included in two seperated template files?

Thank you in advance for your kind help.

**Comment by Whitford** [comment]
@chemlove Sorry for the very slow reply.  I don't usually look to the issues tracker for questions. So, I just now saw your question. What I suggest is that you email the smog-users listserv, and open discussions there.  You can sign up for the forum at
https://mailman.rice.edu/mailman/listinfo/smog-users
