### ISSUE TITLE
Folding Pathway

### ISSUE THREAD

**Issue by EBGU** [smog-server/OpenSMOG#76]
Dear SMOG team,

This is an awesome project! I really appreciate your work!
I am recently working with protein folding pathway prediction, but I am quite new to this area. I wonder if I can find some examples to simulate protein folding processes with an SBM or a hybrid model. Thank you so much!

Best, 
Harold

**Comment by contessoto** [comment]
Hello,
Thanks for your comment.
We have the OpenSMOG documentation which contains tutorials starting from package installation, generation of input files and how to run a SBM simulation using different models.
Here is the documentation link https://opensmog.readthedocs.io.
I also recommend taking a look at SMOG server at https://smog-server.org
OpenSMOG paper is also a good start point: https://onlinelibrary.wiley.com/doi/full/10.1002/pro.4209
Please let us know if you have additional questions.

**Comment by EBGU** [comment]
Thank you for your reply!
Specifically, I am folding an ~250 aa protein(JMJD8). I have its structure and an extended structure generated by https://spin.niddk.nih.gov/bax/nmrserver/pdbutil/ext.html with its sequence.
I generated .gro .top and .xml files for these two PDBs. I want to simulate the folding process so I run a simulation with following commands:

from OpenSMOG import SBM
sbm_AA = SBM(name='JMJD8', time_step=0.002, collision_rate=1.0, r_cutoff=1.2, temperature=0.5)
sbm_AA.setup_openmm(platform='cuda',GPUindex='default')
sbm_AA.saveFolder('output_JMJD8_ext')
sbm_AA_grofile = 'JMJD8_ext.AA.gro'   #from extended pdb 
sbm_AA_topfile = 'JMJD8_ext.AA.top'   #from extended pdb 
sbm_AA_xmlfile = 'JMJD8.AA.xml'         #from target pdb 
sbm_AA.loadSystem(Grofile=sbm_AA_grofile, Topfile=sbm_AA_topfile, Xmlfile=sbm_AA_xmlfile)
sbm_AA.createSimulation()
sbm_AA.createReporters(trajectory=True, energies=True, energy_components=True, interval=10**5)
sbm_AA.run(nsteps=10**8, report=True, interval=10**5)

However, my protein did not fold after 10**8 steps, and I did not see any secondary structure formed. I wonder if I have made any mistake, or I need a much longer simulation.
Thank you!
