### ISSUE TITLE
Cannot set GPUindex in current OpenSMOG

### ISSUE THREAD

**Issue by yangwang123** [smog-server/OpenSMOG#80]
The issue seems to be line 331-336 of OpenSMOG.py:

```python
if GPUindex != "" and GPUindex.lower() != "default":
    if isinstance(GPUindex,int):
         properties["DeviceIndex"] = GPUindex
    else:
         print('Setup incomplete!\nGPUindex must be an integer. Given: {}\nTry rerunning setup_openmm again.'.format(GPUindex))
         return
```

Calling GPUindex.lower() requires GPUindex is a string, but this fails the check for integer. Therefore, both string and integer for GPUindex fails. I believe OpenMM DeviceIndex accepts both string and integer (e.g. 1 or "1"), so integer check is not needed.

**Comment by Whitford** [comment]
Thanks, Yang.  We'll clean this up and get back to you.

**Comment by yangwang123** [comment]
Issue resolved
